tap "homebrew/cask-fonts"

# essentials
brew "bash"
brew "git"
brew "tmux"
brew "neovim"
brew "htop"
brew "coreutils"
brew "bat"
brew "gh"
brew "gnupg" if OS.mac?

# cli
brew "fd"
brew "ripgrep"
brew "fzf"
brew "gawk"
brew "lsd"
brew "duf"
brew "procs"
brew "lazygit"
brew "starship"
brew "gnu-sed"
brew "git-delta"

# dev stuff
brew "wget"
brew "curl"
brew "jq"
brew "scc"
brew "tldr"
brew "hyperfine"
brew "httpie"
brew "sqlite"

# work
brew "awscli"
brew "libpq"
brew "pipenv"
brew "pyenv"
cask "zoom"
cask "insomnia"

# other
brew "nvm"
brew "dog" # better dig
brew "asciinema" # record terminal

# kubernetes & docker
brew "kubernetes-cli"
brew "helm"
brew "istioctl"
